sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kSGp0DqYQlFqvzoTL6sUoYNIPKgiEV3Wsg96dCz3sFbCYAipAIXNOce4axyD8VK2W7uOvY6bybb96R+KYrJspY1MXJoZnS99hIQTVwVLmR8KAefGlDpIKQsKOILEfpn/QC23PKHjvvXzL4NGI7mm61VDfxYY6UQCnl62HNVCYKGsLb0kzwHhbW0r8QgvkK7yRnQNHCvc217B+SccwnG/Z1mTACK3PWwx99/qiOq1wrrmuP/FhGl4Vu0VE+fEzijpN366VYuSoLpoQ7DWP3rmTVdV9Er7ckblVuMNqKfbF83yS2UjxoEggiIHrW67IOndvEaNvvioQGuYOqW/0FITbRSfANPgIGwb6kXSS0d/ZNox2bmHuoKhvvjN7RyrcxheNcq/k025jUm9Z7MHlirNawS5mSDuwyyaLwi6xXXxH9iBGEWA+mkC0TTeMpX+ybK6IFhyKgkjpLbhFi1eEcw2cEvkekyNMKwQSwXzaUwslhiof8VIvHdQScyU/iQ5ES7p6PzxZkE5zkHDWqVheodiO9OB7xdsBvri444+48yQ/XnDQcmAXALJwcvMAVIljZ3xgafnJq/cMfMZt+b29S8nwb7isP3+refer4NWqGg5TO9aWZnmi37o0IjKSyyOor4DUkx+yFnDfB1z1YPpi58RuIfT3jEv8rrbb9qdBv1G03g=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Poems-of-Sidney-Lanier_579
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy